name: CI Pipeline

# on:
#   push:
#     branches: [ develop ]
#   pull_request:
#     branches: [ develop ]
  schedule:
    - cron: '55 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print current branch
      run: echo "Current branch is ${{ github.ref }}"
      
    - name: Print current time
      run: date
