name: CI Pipeline

on:
  schedule:
    - cron: '10 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current time
      run: date

    - name: Run tests
      run: npm test
